# Notes:
#
# First match wins
#
# queryRegex = Java regex syntax
#
# functionScores - See the following for function score syntax
# https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-function-score-query.html

queryConfigurations:
  # Select *
  - queryRegex: '[*]|'
    simpleQuery: false
    prefixMatchQuery: false
    exactMatchQuery: false
    boolQuery:
      must_not:
        term:
          deprecated:
            value: true
    functionScore:
      functions:
        - filter:
            term:
              materialized:
                value: true
          weight: 0.8
      score_mode: multiply
      boost_mode: multiply

  # Criteria for exact-match only
  # Contains quoted then use exact match query
  - queryRegex: >-
      ["'].+["']
    simpleQuery: false
    prefixMatchQuery: true
    exactMatchQuery: true
    functionScore:
      functions:
        - filter:
            term:
              materialized:
                value: true
          weight: 0.8
        - filter:
            term:
              deprecated:
                value: true
          weight: 0
      score_mode: multiply
      boost_mode: multiply

  # default
  - queryRegex: .*
    simpleQuery: true
    prefixMatchQuery: true
    exactMatchQuery: true
    boolQuery:
      must_not:
        term:
          deprecated:
            value: true
    functionScore:
      functions:
        - filter:
            term:
              materialized:
                value: true
          weight: 0.8
      score_mode: multiply
      boost_mode: multiply
