FROM acryldata/datahub-gms:v0.13.3

COPY ./datahub/datahub-v0.13.3/metadata-service/war/build/libs/war.war /datahub/datahub-gms/bin/war.war
COPY ./external/jetty-runner-11.0.26.jar /jetty-runner.jar

